Review.create(title: "plan 9 from outer space", fresh: true, body: Faker::Lorem.paragraphs.join)
Review.create(title: "braveheart", fresh: false, body: Faker::Lorem.paragraphs.join)
Review.create(title: "sabatoge", fresh: true, body: Faker::Lorem.paragraphs.join)
Review.create(title: "beauty and the beast", fresh: false, body: Faker::Lorem.paragraphs.join)
Review.create(title: "the dark night", fresh: true, body: Faker::Lorem.paragraphs.join)
Review.create(title: "looper", fresh: false, body: Faker::Lorem.paragraphs.join)
Review.create(title: "the imitation game", fresh: false, body: Faker::Lorem.paragraphs.join)
Review.create(title: "selma", fresh: false, body: Faker::Lorem.paragraphs.join)
Review.create(title: "saturday night fever", fresh: false, body: Faker::Lorem.paragraphs.join)
Review.create(title: "finding nemo", fresh: true, body: Faker::Lorem.paragraphs.join)
Review.create(title: "billy the kid vs dracula", fresh: true, body: Faker::Lorem.paragraphs.join)
Review.create(title: "the shawshank redemption", fresh: false, body: Faker::Lorem.paragraphs.join)
Review.create(title: "pulp fiction", fresh: false, body: Faker::Lorem.paragraphs.join)
